<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>FreeCAD on Some Title</title>
    <link>https://japan2018.github.io/tags/freecad/</link>
    <description>Recent content in FreeCAD on Some Title</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Sun, 03 Nov 2019 00:00:00 +0000</lastBuildDate>
    
	<atom:link href="https://japan2018.github.io/tags/freecad/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>Freecad&#39;s memorandum (for yourself)</title>
      <link>https://japan2018.github.io/freecads-memorandum-for-yourself-fc558/</link>
      <pubDate>Sun, 03 Nov 2019 00:00:00 +0000</pubDate>
      
      <guid>https://japan2018.github.io/freecads-memorandum-for-yourself-fc558/</guid>
      <description>A memorandum for yourself.  Create a primitive sphere and export with iges (specify radius and position) import FreeCAD as APP import Part freecad = APP.newDocument(&amp;#34;model&amp;#34;) comp_1 = Part.Sphere() comp_1.Radius=10 myPart = freecad.addObject(&amp;#34;Part::Feature&amp;#34;,&amp;#34;comp_1&amp;#34;) myPart.Shape= comp_1.toShape() myPart.Placement = App.Placement(App.Vector(100,0,0),App.Rotation(App.Vector(0,0,1),0)) freecad.recompute() myPart.Shape.MatrixOfInertia freecad.saveAs(&amp;#34;comp_1.FCStd&amp;#34;) Part.export([freecad.Objects[0]],&amp;#34;comp_1.iges&amp;#34;) </description>
    </item>
    
  </channel>
</rss>